package gdx.liftoff.game;

import com.badlogic.gdx.utils.ObjectIntMap;

@SuppressWarnings("PointlessArithmeticExpression")
public final class AssetNames {
    /**
     * No need to instantiate.
     */
    private AssetNames() {}

    public static final int DIRT                 =   0 +  0;
    public static final int GRASS                =   1 +  0;
    public static final int BASALT               =   2 +  0;
    public static final int SAND                 =   3 +  0;
    public static final int HALF_WATER_FGH       =   4 +  0;
    public static final int HALF_WATER_FH        =   5 +  0;
    public static final int HALF_WATER_GH        =   6 +  0;
    public static final int HALF_WATER_H         =   7 +  0;
    public static final int DECO_ROCKS           =   8 +  0;
    public static final int DECO_BOULDER         =   9 +  0;
    public static final int DECO_CATTAIL         =  10 +  0;
    public static final int HALF_DIRT            =   0 + 11;
    public static final int HALF_GRASS           =   1 + 11;
    public static final int HALF_BASALT          =   2 + 11;
    public static final int HALF_SAND            =   3 + 11;
    public static final int BASE_WATER_FGH       =   4 + 11;
    public static final int BASE_WATER_FH        =   5 + 11;
    public static final int BASE_WATER_GH        =   6 + 11;
    public static final int BASE_WATER_H         =   7 + 11;
    public static final int DECO_BUSH            =   8 + 11;
    public static final int DECO_STUMP           =   9 + 11;
    public static final int DECO_FLAME           =  10 + 11;
    public static final int SNOW                 =   0 + 22;
    public static final int ICE                  =   1 + 22;
    public static final int LAVA                 =   2 + 22;
    public static final int DRY                  =   3 + 22;
    public static final int HALF_SWAMP_FGH       =   4 + 22;
    public static final int HALF_SWAMP_FH        =   5 + 22;
    public static final int HALF_SWAMP_GH        =   6 + 22;
    public static final int HALF_SWAMP_H         =   7 + 22;
    public static final int DECO_BUNDLE          =   8 + 22;
    public static final int DECO_HEDGE           =   9 + 22;
    public static final int DECO_CRYSTALS        =  10 + 22;
    public static final int HALF_SNOW            =   0 + 33;
    public static final int HALF_ICE             =   1 + 33;
    public static final int HALF_LAVA            =   2 + 33;
    public static final int HALF_DRY             =   3 + 33;
    public static final int BASE_SWAMP_FGH       =   4 + 33;
    public static final int BASE_SWAMP_FH        =   5 + 33;
    public static final int BASE_SWAMP_GH        =   6 + 33;
    public static final int BASE_SWAMP_H         =   7 + 33;
    public static final int DECO_LOG             =   8 + 33;
    public static final int DECO_CACTUS          =   9 + 33;
    public static final int DECO_SPIKE           =  10 + 33;
    public static final int PATH_GRASS_GR        =   0 + 44;
    public static final int PATH_GRASS_FT        =   1 + 44;
    public static final int PATH_GRASS_FTR       =   2 + 44;
    public static final int PATH_GRASS_FGT       =   3 + 44;
    public static final int PATH_GRASS_FGTR      =   4 + 44;
    public static final int PATH_GRASS_GTR       =   5 + 44;
    public static final int PATH_GRASS_FGR       =   6 + 44;
    public static final int PATH_GRASS_FG        =   7 + 44;
    public static final int PATH_GRASS_GT        =   8 + 44;
    public static final int PATH_GRASS_TR        =   9 + 44;
    public static final int PATH_GRASS_FR        =  10 + 44;
    public static final int HALF_PATH_GRASS_GR   =   0 + 55;
    public static final int HALF_PATH_GRASS_FT   =   1 + 55;
    public static final int HALF_PATH_GRASS_FTR  =   2 + 55;
    public static final int HALF_PATH_GRASS_FGT  =   3 + 55;
    public static final int HALF_PATH_GRASS_FGTR =   4 + 55;
    public static final int HALF_PATH_GRASS_GTR  =   5 + 55;
    public static final int HALF_PATH_GRASS_FGR  =   6 + 55;
    public static final int HALF_PATH_GRASS_FG   =   7 + 55;
    public static final int HALF_PATH_GRASS_GT   =   8 + 55;
    public static final int HALF_PATH_GRASS_TR   =   9 + 55;
    public static final int HALF_PATH_GRASS_FR   =  10 + 55;
    public static final int PATH_DRY_GR          =   0 + 66;
    public static final int PATH_DRY_FT          =   1 + 66;
    public static final int PATH_DRY_FTR         =   2 + 66;
    public static final int PATH_DRY_FGT         =   3 + 66;
    public static final int PATH_DRY_FGTR        =   4 + 66;
    public static final int PATH_DRY_GTR         =   5 + 66;
    public static final int PATH_DRY_FGR         =   6 + 66;
    public static final int PATH_DRY_FG          =   7 + 66;
    public static final int PATH_DRY_GT          =   8 + 66;
    public static final int PATH_DRY_TR          =   9 + 66;
    public static final int PATH_DRY_FR          =  10 + 66;
    public static final int HALF_PATH_DRY_GR     =   0 + 77;
    public static final int HALF_PATH_DRY_FT     =   1 + 77;
    public static final int HALF_PATH_DRY_FTR    =   2 + 77;
    public static final int HALF_PATH_DRY_FGT    =   3 + 77;
    public static final int HALF_PATH_DRY_FGTR   =   4 + 77;
    public static final int HALF_PATH_DRY_GTR    =   5 + 77;
    public static final int HALF_PATH_DRY_FGR    =   6 + 77;
    public static final int HALF_PATH_DRY_FG     =   7 + 77;
    public static final int HALF_PATH_DRY_GT     =   8 + 77;
    public static final int HALF_PATH_DRY_TR     =   9 + 77;
    public static final int HALF_PATH_DRY_FR     =  10 + 77;
    public static final int SANDSTONE            =   0 + 88;
    public static final int SLATE                =   1 + 88;
    public static final int BRICK                =   2 + 88;
    public static final int WOOD                 =   3 + 88;
    public static final int CAP_SANDSTONE        =   4 + 88;
    public static final int CAP_SLATE            =   5 + 88;
    public static final int CAP_WOOD             =   6 + 88;
    public static final int CAP_THATCHED         =   7 + 88;
    public static final int DECO_BED_GR          =   8 + 88;
    public static final int DECO_BED_FT          =   9 + 88;
    public static final int DECO_FENCE_GR        =  10 + 88;
    public static final int HALF_SANDSTONE       =   0 + 99;
    public static final int HALF_SLATE           =   1 + 99;
    public static final int HALF_BRICK           =   2 + 99;
    public static final int HALF_WOOD            =   3 + 99;
    public static final int BASE_SANDSTONE       =   4 + 99;
    public static final int BASE_SLATE           =   5 + 99;
    public static final int BASE_WOOD            =   6 + 99;
    public static final int BASE_THATCHED        =   7 + 99;
    public static final int HALF_DECO_BED_GR     =   8 + 99;
    public static final int HALF_DECO_BED_FT     =   9 + 99;
    public static final int DECO_FENCE_FT        =  10 + 99;

    public static final ObjectIntMap<String> NAMES = new ObjectIntMap<>(128);
    static {
        NAMES.put("dirt"                 ,   0 +  0);
        NAMES.put("grass"                ,   1 +  0);
        NAMES.put("basalt"               ,   2 +  0);
        NAMES.put("sand"                 ,   3 +  0);
        NAMES.put("half water fgh"       ,   4 +  0);
        NAMES.put("half water fh"        ,   5 +  0);
        NAMES.put("half water gh"        ,   6 +  0);
        NAMES.put("half water h"         ,   7 +  0);
        NAMES.put("deco rocks"           ,   8 +  0);
        NAMES.put("deco boulder"         ,   9 +  0);
        NAMES.put("deco cattail"         ,  10 +  0);
        NAMES.put("half dirt"            ,   0 + 11);
        NAMES.put("half grass"           ,   1 + 11);
        NAMES.put("half basalt"          ,   2 + 11);
        NAMES.put("half sand"            ,   3 + 11);
        NAMES.put("base water fgh"       ,   4 + 11);
        NAMES.put("base water fh"        ,   5 + 11);
        NAMES.put("base water gh"        ,   6 + 11);
        NAMES.put("base water h"         ,   7 + 11);
        NAMES.put("deco bush"            ,   8 + 11);
        NAMES.put("deco stump"           ,   9 + 11);
        NAMES.put("deco flame"           ,  10 + 11);
        NAMES.put("snow"                 ,   0 + 22);
        NAMES.put("ice"                  ,   1 + 22);
        NAMES.put("lava"                 ,   2 + 22);
        NAMES.put("dry"                  ,   3 + 22);
        NAMES.put("half swamp fgh"       ,   4 + 22);
        NAMES.put("half swamp fh"        ,   5 + 22);
        NAMES.put("half swamp gh"        ,   6 + 22);
        NAMES.put("half swamp h"         ,   7 + 22);
        NAMES.put("deco bundle"          ,   8 + 22);
        NAMES.put("deco hedge"           ,   9 + 22);
        NAMES.put("deco crystals"        ,  10 + 22);
        NAMES.put("half snow"            ,   0 + 33);
        NAMES.put("half ice"             ,   1 + 33);
        NAMES.put("half lava"            ,   2 + 33);
        NAMES.put("half dry"             ,   3 + 33);
        NAMES.put("base swamp fgh"       ,   4 + 33);
        NAMES.put("base swamp fh"        ,   5 + 33);
        NAMES.put("base swamp gh"        ,   6 + 33);
        NAMES.put("base swamp h"         ,   7 + 33);
        NAMES.put("deco log"             ,   8 + 33);
        NAMES.put("deco cactus"          ,   9 + 33);
        NAMES.put("deco spike"           ,  10 + 33);
        NAMES.put("path grass gr"        ,   0 + 44);
        NAMES.put("path grass ft"        ,   1 + 44);
        NAMES.put("path grass ftr"       ,   2 + 44);
        NAMES.put("path grass fgt"       ,   3 + 44);
        NAMES.put("path grass fgtr"      ,   4 + 44);
        NAMES.put("path grass gtr"       ,   5 + 44);
        NAMES.put("path grass fgr"       ,   6 + 44);
        NAMES.put("path grass fg"        ,   7 + 44);
        NAMES.put("path grass gt"        ,   8 + 44);
        NAMES.put("path grass tr"        ,   9 + 44);
        NAMES.put("path grass fr"        ,  10 + 44);
        NAMES.put("half path grass gr"   ,   0 + 55);
        NAMES.put("half path grass ft"   ,   1 + 55);
        NAMES.put("half path grass ftr"  ,   2 + 55);
        NAMES.put("half path grass fgt"  ,   3 + 55);
        NAMES.put("half path grass fgtr" ,   4 + 55);
        NAMES.put("half path grass gtr"  ,   5 + 55);
        NAMES.put("half path grass fgr"  ,   6 + 55);
        NAMES.put("half path grass fg"   ,   7 + 55);
        NAMES.put("half path grass gt"   ,   8 + 55);
        NAMES.put("half path grass tr"   ,   9 + 55);
        NAMES.put("half path grass fr"   ,  10 + 55);
        NAMES.put("path dry gr"          ,   0 + 66);
        NAMES.put("path dry ft"          ,   1 + 66);
        NAMES.put("path dry ftr"         ,   2 + 66);
        NAMES.put("path dry fgt"         ,   3 + 66);
        NAMES.put("path dry fgtr"        ,   4 + 66);
        NAMES.put("path dry gtr"         ,   5 + 66);
        NAMES.put("path dry fgr"         ,   6 + 66);
        NAMES.put("path dry fg"          ,   7 + 66);
        NAMES.put("path dry gt"          ,   8 + 66);
        NAMES.put("path dry tr"          ,   9 + 66);
        NAMES.put("path dry fr"          ,  10 + 66);
        NAMES.put("half path dry gr"     ,   0 + 77);
        NAMES.put("half path dry ft"     ,   1 + 77);
        NAMES.put("half path dry ftr"    ,   2 + 77);
        NAMES.put("half path dry fgt"    ,   3 + 77);
        NAMES.put("half path dry fgtr"   ,   4 + 77);
        NAMES.put("half path dry gtr"    ,   5 + 77);
        NAMES.put("half path dry fgr"    ,   6 + 77);
        NAMES.put("half path dry fg"     ,   7 + 77);
        NAMES.put("half path dry gt"     ,   8 + 77);
        NAMES.put("half path dry tr"     ,   9 + 77);
        NAMES.put("half path dry fr"     ,  10 + 77);
        NAMES.put("sandstone"            ,   0 + 88);
        NAMES.put("slate"                ,   1 + 88);
        NAMES.put("brick"                ,   2 + 88);
        NAMES.put("wood"                 ,   3 + 88);
        NAMES.put("cap sandstone"        ,   4 + 88);
        NAMES.put("cap slate"            ,   5 + 88);
        NAMES.put("cap wood"             ,   6 + 88);
        NAMES.put("cap thatched"         ,   7 + 88);
        NAMES.put("deco bed gr"          ,   8 + 88);
        NAMES.put("deco bed ft"          ,   9 + 88);
        NAMES.put("deco fence gr"        ,  10 + 88);
        NAMES.put("half sandstone"       ,   0 + 99);
        NAMES.put("half slate"           ,   1 + 99);
        NAMES.put("half brick"           ,   2 + 99);
        NAMES.put("half wood"            ,   3 + 99);
        NAMES.put("base sandstone"       ,   4 + 99);
        NAMES.put("base slate"           ,   5 + 99);
        NAMES.put("base wood"            ,   6 + 99);
        NAMES.put("base thatched"        ,   7 + 99);
        NAMES.put("half deco bed gr"     ,   8 + 99);
        NAMES.put("half deco bed ft"     ,   9 + 99);
        NAMES.put("deco fence ft"        ,  10 + 99);
    }
}
